_target_: src.models.SFMModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  # mode: min
  # factor: 0.1
  #Â patience: 10
  T_max: 1000
  eta_min: 0.00008

net:
  _target_: src.models.net.promoter_model.promoter_model.PromoterModel
  mode: dirichlet
  embed_dim: 256
  time_step: 0.01

compile: false
