_target_: src.models.PromoterModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005
  weight_decay: 0.0

scheduler: null

model:
  _target_: src.models.net.promoter_model.PromoterModel
  mode: dirichlet
  embed_dim: 256
  time_dependent_weights: null
  time_step: 0.01

compile: false

mode: dirichlet

# validate
validate: false

# run settings
distill_ckpt: null # cls model for evaluation purposes
distill_ckpt_hparams: null

# model
fix_alpha: null
alpha_scale: 2
alpha_max: 8
prior_pseudocount: 2
flow_temp: 1.0
num_integration_steps: 100

# logging
print_freq: 100

# misc.
ckpt_iterations: null