_target_: src.models.DNAModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.net.model.CNNModel
  hidden: 128
  mode: simplex
  num_cls: 3
  depth: 1
  dropout: 0.0
  prior_pseudocount: 2.0
  cls_expanded_simplex: False
  clean_data: False
  classifier: False
  classifier_free_guidance: False
  activation: relu


compile: false
